#import "KPBehaviorHooks.h"
#import <UIKit/UIKit.h>
#import <objc/runtime.h>

static BOOL KPOn(NSString *key) { return [[NSUserDefaults standardUserDefaults] boolForKey:key]; }
static NSMutableSet<NSString *> *KPHooked;
static NSString *KPMethodKey(Class cls, SEL sel) { return [NSString stringWithFormat:@"%@::%@",NSStringFromClass(cls),NSStringFromSelector(sel)]; }
static BOOL KPClaim(Class cls, SEL sel) { if (!KPHooked) KPHooked=[NSMutableSet set]; NSString *k=KPMethodKey(cls,sel); if ([KPHooked containsObject:k]) return NO; [KPHooked addObject:k]; return YES; }

static NSArray<Class> *KPClasses(void) { int count=objc_getClassList(NULL,0); if (count<=0) return @[]; Class *buf=(Class *)calloc((size_t)count,sizeof(Class)); count=objc_getClassList(buf,count); NSMutableArray *out=[NSMutableArray arrayWithCapacity:(NSUInteger)count]; for(int i=0;i<count;i++) if(buf[i]) [out addObject:buf[i]]; free(buf); return out; }
static void KPHookBool0(SEL sel, NSString *key) { for (Class cls in KPClasses()) { Method m=class_getInstanceMethod(cls,sel); if(!m || !KPClaim(cls,sel)) continue; IMP orig=method_getImplementation(m); id block=^BOOL(id self){ if(KPOn(key)) return NO; return ((BOOL(*)(id,SEL))orig)(self,sel); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }
static void KPHookBool1(SEL sel, NSString *key) { for (Class cls in KPClasses()) { Method m=class_getInstanceMethod(cls,sel); if(!m || !KPClaim(cls,sel)) continue; IMP orig=method_getImplementation(m); id block=^BOOL(id self,id a){ if(KPOn(key)) return NO; return ((BOOL(*)(id,SEL,id))orig)(self,sel,a); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }
static void KPHookVoid0(SEL sel, NSString *key) { for (Class cls in KPClasses()) { Method m=class_getInstanceMethod(cls,sel); if(!m || !KPClaim(cls,sel)) continue; IMP orig=method_getImplementation(m); id block=^(id self){ if(KPOn(key)) return; ((void(*)(id,SEL))orig)(self,sel); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }
static void KPHookVoid3(SEL sel, NSString *key) { for (Class cls in KPClasses()) { Method m=class_getInstanceMethod(cls,sel); if(!m || !KPClaim(cls,sel)) continue; IMP orig=method_getImplementation(m); id block=^(id self,id a,id b,id c){ if(KPOn(key)) return; ((void(*)(id,SEL,id,id,id))orig)(self,sel,a,b,c); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }
static void KPHookVoid4(SEL sel, NSString *key) { for (Class cls in KPClasses()) { Method m=class_getInstanceMethod(cls,sel); if(!m || !KPClaim(cls,sel)) continue; IMP orig=method_getImplementation(m); id block=^(id self,id a,id b,id c,id d){ if(KPOn(key)) return; ((void(*)(id,SEL,id,id,id,id))orig)(self,sel,a,b,c,d); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }

static UIViewController *KPTop(UIViewController *vc) { if(!vc)return nil; if(vc.presentedViewController)return KPTop(vc.presentedViewController); if([vc isKindOfClass:UINavigationController.class])return KPTop(((UINavigationController*)vc).visibleViewController); if([vc isKindOfClass:UITabBarController.class])return KPTop(((UITabBarController*)vc).selectedViewController); return vc; }
static UIViewController *KPCurrentTop(void) { for(UIScene *s in UIApplication.sharedApplication.connectedScenes) if([s isKindOfClass:UIWindowScene.class]&&s.activationState==UISceneActivationStateForegroundActive) for(UIWindow *w in ((UIWindowScene*)s).windows) if(w.isKeyWindow) return KPTop(w.rootViewController); return KPTop(UIApplication.sharedApplication.windows.firstObject.rootViewController); }
static void KPConfirmCall(NSString *title, void (^call)(void)) { dispatch_async(dispatch_get_main_queue(), ^{ UIViewController *top=KPCurrentTop(); if(!top){call();return;} UIAlertController *a=[UIAlertController alertControllerWithTitle:title message:nil preferredStyle:UIAlertControllerStyleAlert]; [a addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]]; [a addAction:[UIAlertAction actionWithTitle:@"Continue" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){call();}]]; [top presentViewController:a animated:YES completion:nil]; }); }
static void KPHookConfirm0(SEL sel, NSString *key, NSString *title) { for(Class cls in KPClasses()){ Method m=class_getInstanceMethod(cls,sel); if(!m||!KPClaim(cls,sel))continue; IMP orig=method_getImplementation(m); id block=^(id self){ if(!KPOn(key)){((void(*)(id,SEL))orig)(self,sel);return;} KPConfirmCall(title,^{((void(*)(id,SEL))orig)(self,sel);}); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }
static void KPHookConfirm1(SEL sel, NSString *key, NSString *title) { for(Class cls in KPClasses()){ Method m=class_getInstanceMethod(cls,sel); if(!m||!KPClaim(cls,sel))continue; IMP orig=method_getImplementation(m); id block=^(id self,id arg){ if(!KPOn(key)){((void(*)(id,SEL,id))orig)(self,sel,arg);return;} KPConfirmCall(title,^{((void(*)(id,SEL,id))orig)(self,sel,arg);}); }; class_replaceMethod(cls,sel,imp_implementationWithBlock(block),method_getTypeEncoding(m)); } }

static NSString *KPViewText(UIView *v) { NSMutableArray *p=[NSMutableArray array]; if(v.accessibilityLabel.length)[p addObject:v.accessibilityLabel]; if([v isKindOfClass:UILabel.class]&&((UILabel*)v).text.length)[p addObject:((UILabel*)v).text]; if([v isKindOfClass:UIButton.class]){ NSString *t=[((UIButton*)v) titleForState:UIControlStateNormal]; if(t.length)[p addObject:t]; } return [[p componentsJoinedByString:@" "] lowercaseString]; }
static BOOL KPAncestorLooksLikeTab(UIView *v){ for(UIView *x=v;x;x=x.superview){ if([x isKindOfClass:UITabBar.class])return YES; NSString *n=NSStringFromClass(x.class).lowercaseString; if([n containsString:@"tabbar"]||[n containsString:@"pivotbar"]||[n containsString:@"bottombar"])return YES; } return NO; }
static void KPSanitizeView(UIView *v, BOOL ttk){ NSString *t=KPViewText(v); if(ttk && KPAncestorLooksLikeTab(v)){ if(KPOn(@"TTKPlus_HideFriendsTab")&&[t containsString:@"friends"])v.hidden=YES; if(KPOn(@"TTKPlus_HideCreateTab")&&([t containsString:@"create"]||[t isEqualToString:@"+"]))v.hidden=YES; if(KPOn(@"TTKPlus_HideInboxTab")&&[t containsString:@"inbox"])v.hidden=YES; } if(!ttk){ if(KPAncestorLooksLikeTab(v)){ if(KPOn(@"kEnableiKGHDHideYTShorts")&&[t containsString:@"shorts"])v.hidden=YES; if(KPOn(@"kEnableiKGHDDisableCreate")&&[t containsString:@"create"])v.hidden=YES; if(KPOn(@"kEnableiKGHDHideSearch")&&[t containsString:@"search"])v.hidden=YES; } if(KPOn(@"kEnableiKGHDHideCastButton")&&[t containsString:@"cast"])v.hidden=YES; if(KPOn(@"kEnableiKGHDHideComments")&&[t containsString:@"comments"])v.hidden=YES; if(KPOn(@"kEnableiKGHDHidePlayList")&&[t containsString:@"playlist"])v.hidden=YES; if(KPOn(@"kEnableiKGHDHideCaptionsToggle")&&([t containsString:@"caption"]||[t containsString:@"subtitles"]))v.hidden=YES; if(KPOn(@"kEnableiKGHDHideAutoplayToggle")&&[t containsString:@"autoplay"])v.hidden=YES; if(KPOn(@"kEnableiKGHDNoPremiumpopup")&&[t containsString:@"youtube premium"])v.hidden=YES; } for(UIView *s in v.subviews)KPSanitizeView(s,ttk); }
static void KPSanitizeWindows(BOOL ttk){ dispatch_async(dispatch_get_main_queue(),^{ for(UIScene *s in UIApplication.sharedApplication.connectedScenes) if([s isKindOfClass:UIWindowScene.class]) for(UIWindow *w in ((UIWindowScene*)s).windows) KPSanitizeView(w,ttk); }); }

void KPInstallTTKBehaviorHooks(void){ dispatch_after(dispatch_time(DISPATCH_TIME_NOW,3*NSEC_PER_SEC),dispatch_get_main_queue(),^{ KPHookBool0(NSSelectorFromString(@"p_shouldReportProfileView"),@"TTKPlus_AnonymousProfileView"); KPHookBool1(NSSelectorFromString(@"p_shouldReportHasVeiwedProfileForUser:"),@"TTKPlus_AnonymousProfileView"); KPHookVoid0(NSSelectorFromString(@"reportProfileView"),@"TTKPlus_AnonymousProfileView"); KPHookVoid3(NSSelectorFromString(@"reportStoryViewedWithStoryID:uid:completion:"),@"TTKPlus_StoryEye"); KPHookVoid4(NSSelectorFromString(@"reportStoryViewedWithStoryID:uid:unlocked:completion:"),@"TTKPlus_StoryEye"); KPHookVoid4(NSSelectorFromString(@"clientMarkConversationAsRead:tillMessagePullIndex:serverMessageID:sendToServer:"),@"TTKPlus_MsgEye"); KPHookConfirm1(NSSelectorFromString(@"onFollowViewClicked:"),@"TTKPlus_FollowConfirmation",@"Follow this account?"); KPHookConfirm1(NSSelectorFromString(@"onLikeAction:"),@"TTKPlus_LikeConfirmation",@"Like this video?"); KPHookConfirm0(NSSelectorFromString(@"onLikeButtonClicked"),@"TTKPlus_LikeConfirmation",@"Like this video?"); [NSTimer scheduledTimerWithTimeInterval:1.5 repeats:YES block:^(__unused NSTimer *timer){KPSanitizeWindows(YES);}]; }); }
void KPInstallYTKBehaviorHooks(void){ dispatch_after(dispatch_time(DISPATCH_TIME_NOW,3*NSEC_PER_SEC),dispatch_get_main_queue(),^{ [NSTimer scheduledTimerWithTimeInterval:1.5 repeats:YES block:^(__unused NSTimer *timer){KPSanitizeWindows(NO);}]; }); }
